### PR TITLE
Add dotenv-fastify for Fastify reference code

### PR DESCRIPTION
**Pull request by lirantal**
This adds a sample application which aims to provide Node.js developers who wish to build upon the [Fastify application framework](https://www.fastify.io) and uses dotenv as the configuration management library of choice.

In this example code:
- It shows how to use a decent Fastify application server setup with separated server and application instances
- It splits routes to their own dedicated files (a simple hello world one)
- It uses `dotenv` as a Fastify plugin
- It uses Fastify's `decorate` feature to provide framework-wide access to the configuration object parsed by dotenv

As such, it aims to be a good and recommended reference code for those wishing to build on top of Fastify with dotenv.

### CODE REVIEW

**Comment by lirantal** [comment]
@motdotla can I kindly ping you on this pull request to extend and add more examples to build upon dotenv? :-)

**Comment by lirantal** [comment]
@motdotla realize you're busy :-)
Any chance we can land this PR too? (it followed another one you merged, see on the PR log above)

**Comment by motdotla** [comment]
Sorry for the long delay on this @lirantal. Merged.

**Comment by lirantal** [comment]
No worries, all good! :)

**Pull request merged**
